pipeline {
    agent {
        label 'docker'
    }
    environment {
        BASE_IMAGE = "docker-repo.vpc.locusdev.net.../..."
    }

    stages {
        stage('Development') {
            steps {
                script {
                    echo "Project Level Tests for " + env.BRANCH_NAME
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    echo "End to End and Secondary Tests"
                }
            }
        }
        stage('Stage') {
            steps {
                script {
                    echo "Service Validation and Manual Testing"
                }
            }
        }
        stage('Production') {
            steps {
                script {
                    echo "Production Promotion"
                }
            }
        }
    }
    post {
        always {
            script{
                sh 'docker system prune --force'
            }
        }
    }
}
